// Advanced Service Worker with aggressive caching strategies
const CACHE_VERSION = 'v1.0.0';
const STATIC_CACHE = `urvo-static-${CACHE_VERSION}`;
const DYNAMIC_CACHE = `urvo-dynamic-${CACHE_VERSION}`;
const API_CACHE = `urvo-api-${CACHE_VERSION}`;
const IMAGE_CACHE = `urvo-images-${CACHE_VERSION}`;

// Cache strategies
const CACHE_FIRST_ASSETS = [
  // Critical CSS and JS
  /\.(css|js)$/,
  // Fonts
  /\.(woff|woff2|ttf|eot)$/,
  // Images (but we'll handle these separately)
  /\.(png|jpg|jpeg|gif|svg|webp|avif)$/,
];

const NETWORK_FIRST_ASSETS = [
  // API calls
  /\/api\//,
  // Dynamic content
  /\/dashboard\//,
  // User-specific data
  /\/profile/,
  /\/settings/,
];

const STALE_WHILE_REVALIDATE_ASSETS = [
  // Main pages that change occasionally
  /\/(pricing|about|solutions|demo)$/,
  // Static content with potential updates
  /\/(blog|news|documentation)$/,
];

// Cache durations (in seconds)
const CACHE_DURATIONS = {
  STATIC: 30 * 24 * 60 * 60, // 30 days
  DYNAMIC: 7 * 24 * 60 * 60, // 7 days
  API: 60 * 60, // 1 hour
  IMAGES: 30 * 24 * 60 * 60, // 30 days
};

// Install event - cache critical resources
self.addEventListener('install', (event) => {
  console.log('[SW] Installing Service Worker');
  
  event.waitUntil(
    (async () => {
      const staticCache = await caches.open(STATIC_CACHE);
      
      // Cache critical resources immediately
      const criticalResources = [
        '/',
        '/manifest.json',
        // Add critical CSS/JS that should be cached immediately
        // These will be generated by the build process
      ];
      
      try {
        await staticCache.addAll(criticalResources);
        console.log('[SW] Critical resources cached');
      } catch (error) {
        console.error('[SW] Failed to cache critical resources:', error);
      }
      
      // Skip waiting to activate immediately
      self.skipWaiting();
    })()
  );
});

// Activate event - clean up old caches
self.addEventListener('activate', (event) => {
  console.log('[SW] Activating Service Worker');
  
  event.waitUntil(
    (async () => {
      // Clean up old caches
      const cacheNames = await caches.keys();
      const oldCaches = cacheNames.filter(
        name => name.includes('urvo-') && !name.includes(CACHE_VERSION)
      );
      
      await Promise.all(
        oldCaches.map(cacheName => {
          console.log('[SW] Deleting old cache:', cacheName);
          return caches.delete(cacheName);
        })
      );
      
      // Take control of all clients immediately
      await self.clients.claim();
      console.log('[SW] Service Worker activated and claimed clients');
    })()
  );
});

// Fetch event - implement caching strategies
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);
  
  // Skip non-GET requests
  if (request.method !== 'GET') return;
  
  // Skip chrome-extension and other non-http(s) requests
  if (!url.protocol.startsWith('http')) return;
  
  event.respondWith(handleRequest(request));
});

async function handleRequest(request) {
  const url = new URL(request.url);
  const pathname = url.pathname;
  
  try {
    // Handle different types of requests with appropriate strategies
    
    // API requests - Network First with Cache Fallback
    if (NETWORK_FIRST_ASSETS.some(pattern => pattern.test(pathname))) {
      return await networkFirstStrategy(request, API_CACHE);
    }
    
    // Images - Cache First with Network Fallback
    if (/\.(png|jpg|jpeg|gif|svg|webp|avif)$/.test(pathname)) {
      return await cacheFirstStrategy(request, IMAGE_CACHE);
    }
    
    // Static assets - Cache First
    if (CACHE_FIRST_ASSETS.some(pattern => pattern.test(pathname))) {
      return await cacheFirstStrategy(request, STATIC_CACHE);
    }
    
    // Main pages - Stale While Revalidate
    if (STALE_WHILE_REVALIDATE_ASSETS.some(pattern => pattern.test(pathname))) {
      return await staleWhileRevalidateStrategy(request, DYNAMIC_CACHE);
    }
    
    // Default - Network First for HTML pages
    if (request.headers.get('accept')?.includes('text/html')) {
      return await networkFirstStrategy(request, DYNAMIC_CACHE);
    }
    
    // Fallback to network for everything else
    return await fetch(request);
    
  } catch (error) {
    console.error('[SW] Error handling request:', error);
    
    // Return offline fallback for HTML requests
    if (request.headers.get('accept')?.includes('text/html')) {
      return await getOfflineFallback();
    }
    
    throw error;
  }
}

// Cache First Strategy
async function cacheFirstStrategy(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cachedResponse = await cache.match(request);
  
  if (cachedResponse) {
    // Check if cache is still valid
    const cacheTime = cachedResponse.headers.get('sw-cache-time');
    const maxAge = getCacheMaxAge(cacheName);
    
    if (cacheTime && Date.now() - parseInt(cacheTime) < maxAge * 1000) {
      return cachedResponse;
    }
  }
  
  // Fetch from network and cache
  try {
    const networkResponse = await fetch(request);
    
    if (networkResponse.ok) {
      const responseClone = networkResponse.clone();
      
      // Add cache timestamp
      const headers = new Headers(responseClone.headers);
      headers.set('sw-cache-time', Date.now().toString());
      
      const modifiedResponse = new Response(await responseClone.blob(), {
        status: responseClone.status,
        statusText: responseClone.statusText,
        headers
      });
      
      await cache.put(request, modifiedResponse);
    }
    
    return networkResponse;
  } catch (error) {
    // Return cached version if network fails
    if (cachedResponse) {
      return cachedResponse;
    }
    throw error;
  }
}

// Network First Strategy
async function networkFirstStrategy(request, cacheName) {
  const cache = await caches.open(cacheName);
  
  try {
    const networkResponse = await fetch(request);
    
    if (networkResponse.ok) {
      // Cache successful responses
      const responseClone = networkResponse.clone();
      const headers = new Headers(responseClone.headers);
      headers.set('sw-cache-time', Date.now().toString());
      
      const modifiedResponse = new Response(await responseClone.blob(), {
        status: responseClone.status,
        statusText: responseClone.statusText,
        headers
      });
      
      await cache.put(request, modifiedResponse);
    }
    
    return networkResponse;
  } catch (error) {
    // Fall back to cache
    const cachedResponse = await cache.match(request);
    if (cachedResponse) {
      return cachedResponse;
    }
    throw error;
  }
}

// Stale While Revalidate Strategy
async function staleWhileRevalidateStrategy(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cachedResponse = await cache.match(request);
  
  // Start network request (don't await)
  const networkPromise = fetch(request).then(async (networkResponse) => {
    if (networkResponse.ok) {
      const responseClone = networkResponse.clone();
      const headers = new Headers(responseClone.headers);
      headers.set('sw-cache-time', Date.now().toString());
      
      const modifiedResponse = new Response(await responseClone.blob(), {
        status: responseClone.status,
        statusText: responseClone.statusText,
        headers
      });
      
      await cache.put(request, modifiedResponse);
    }
    return networkResponse;
  }).catch(error => {
    console.warn('[SW] Network request failed:', error);
  });
  
  // Return cached response immediately if available
  if (cachedResponse) {
    return cachedResponse;
  }
  
  // If no cache, wait for network
  return await networkPromise;
}

// Get cache max age based on cache name
function getCacheMaxAge(cacheName) {
  if (cacheName.includes('static')) return CACHE_DURATIONS.STATIC;
  if (cacheName.includes('dynamic')) return CACHE_DURATIONS.DYNAMIC;
  if (cacheName.includes('api')) return CACHE_DURATIONS.API;
  if (cacheName.includes('images')) return CACHE_DURATIONS.IMAGES;
  return CACHE_DURATIONS.DYNAMIC; // default
}

// Offline fallback
async function getOfflineFallback() {
  const cache = await caches.open(STATIC_CACHE);
  const offlineResponse = await cache.match('/offline.html');
  
  if (offlineResponse) {
    return offlineResponse;
  }
  
  // Create a basic offline response
  return new Response(
    `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Offline - urvo</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 2rem; text-align: center; background: #f8fafc; }
        .container { max-width: 400px; margin: 0 auto; }
        .icon { font-size: 4rem; margin-bottom: 1rem; }
        .title { font-size: 1.5rem; margin-bottom: 1rem; color: #1e293b; }
        .message { color: #64748b; margin-bottom: 2rem; }
        .button { background: #3b82f6; color: white; padding: 0.75rem 1.5rem; border: none; border-radius: 0.5rem; cursor: pointer; }
        .button:hover { background: #2563eb; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="icon">📱</div>
        <h1 class="title">You're Offline</h1>
        <p class="message">Please check your internet connection and try again.</p>
        <button class="button" onclick="window.location.reload()">Try Again</button>
      </div>
    </body>
    </html>
    `,
    {
      headers: {
        'Content-Type': 'text/html',
        'Cache-Control': 'no-cache'
      }
    }
  );
}

// Background sync for failed requests
self.addEventListener('sync', (event) => {
  if (event.tag === 'background-sync') {
    event.waitUntil(handleBackgroundSync());
  }
});

async function handleBackgroundSync() {
  // Handle failed requests when back online
  console.log('[SW] Background sync triggered');
  // Implementation for retrying failed requests
}

// Push notifications (if needed)
self.addEventListener('push', (event) => {
  if (!event.data) return;
  
  const data = event.data.json();
  
  const options = {
    body: data.body,
    icon: '/icon-192x192.png',
    badge: '/icon-72x72.png',
    tag: data.tag || 'default',
    requireInteraction: false,
    actions: data.actions || []
  };
  
  event.waitUntil(
    self.registration.showNotification(data.title || 'urvo', options)
  );
});

// Handle notification clicks
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  event.waitUntil(
    self.clients.openWindow(event.notification.data?.url || '/')
  );
});

// Periodic background sync for cache cleanup
self.addEventListener('periodicsync', (event) => {
  if (event.tag === 'cache-cleanup') {
    event.waitUntil(cleanupExpiredCaches());
  }
});

async function cleanupExpiredCaches() {
  const cacheNames = await caches.keys();
  
  for (const cacheName of cacheNames) {
    if (!cacheName.includes('urvo-')) continue;
    
    const cache = await caches.open(cacheName);
    const requests = await cache.keys();
    
    for (const request of requests) {
      const response = await cache.match(request);
      if (!response) continue;
      
      const cacheTime = response.headers.get('sw-cache-time');
      const maxAge = getCacheMaxAge(cacheName);
      
      if (cacheTime && Date.now() - parseInt(cacheTime) > maxAge * 1000) {
        await cache.delete(request);
        console.log('[SW] Cleaned up expired cache entry:', request.url);
      }
    }
  }
}

console.log('[SW] Service Worker script loaded');
